In [2]:
import pandas as pd
import numpy as np

In [3]:
f1_diff = pd.read_csv('f1_diff.csv')
f3_diff = pd.read_csv('f3_diff.csv')
f5_diff = pd.read_csv('f5_diff.csv')
f6_diff = pd.read_csv('f6_diff.csv')

In [4]:
f1_diff

     Unnamed: 0 word1 word2  pred_sl  pred_sd  act_sl  act_sd  pred_act_gap
0             0     长    狭窄     0.67     0.49    0.27    0.32          0.40
1             1    内疚    羞愧     5.00     0.00    4.36    1.34          0.64
2             2    暴力    被动     0.20     0.41    0.00    0.00          0.20
3             3     闷    平庸     1.80     0.41    0.91    1.14          0.89
4             4    害羞    昂贵     0.00     0.00    0.00    0.00          0.00
..          ...   ...   ...      ...      ...     ...     ...           ...
467         467    离开    走开     5.60     0.51    4.09    1.32          1.51
468         468     读    理解     3.40     0.51    0.64    1.26          2.76
469         469    装作    想像     2.33     0.49    0.18    0.63          2.15
470         470    跟随    追逐     4.07     0.26    2.82    1.56          1.25
471         471     加     除     0.67     0.49    0.45    0.84          0.22

[472 rows x 8 columns]

In [5]:
type(f1_diff['pred_act_gap'])

pandas.core.series.Series

In [6]:
avg_df = pd.DataFrame({
    'word1': f1_diff['word1'],
    'word2': f1_diff['word2'],
    'pred_sl_f1': f1_diff['pred_sl'],
    'pred_sl_f3': [np.nan] * 3 + list(f3_diff['pred_sl']),
    'pred_sl_f5': f5_diff['pred_sl'],
    'pred_sl_f6': f6_diff['pred_sl'],
    'act_sl_f1': f1_diff['act_sl'],
    'act_sl_f3': [np.nan] * 3 + list(f3_diff['act_sl']),
    'act_sl_f5': f5_diff['act_sl'],
    'act_sl_f6': f6_diff['act_sl'],
})
avg_df

,word1,word2,pred_sl_f1,pred_sl_f3,pred_sl_f5,pred_sl_f6,act_sl_f1,act_sl_f3,act_sl_f5,act_sl_f6
0,长,狭窄,0.67,NaN,0.4,0.60,0.27,NaN,0.27,0.27
1,内疚,羞愧,5.00,NaN,4.9,5.07,4.36,NaN,4.36,4.36
2,暴力,被动,0.20,NaN,0.0,0.07,0.00,NaN,0.00,0.00
3,闷,平庸,1.80,1.87,2.2,1.13,0.91,0.91,0.91,0.91
4,害羞,昂贵,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...
467,离开,走开,5.60,5.60,6.0,5.33,4.09,4.09,4.09,4.09
468,读,理解,3.40,3.80,3.7,3.27,0.64,0.64,0.64,0.64
469,装作,想像,2.33,2.80,2.0,2.73,0.18,0.18,0.18,0.18
470,跟随,追逐,4.07,4.00,4.1,3.93,2.82,2.82,2.82,2.82
471,加,除,0.67,0.67,0.6,1.13,0.45,0.45,0.45,0.45

In [7]:
pred_cols = [f'pred_sl_f{i}' for i in [1,3,5,6]]
act_cols = [f'act_sl_f{i}' for i in [1,3,5,6]]
avg_df['avg_pred_sl'] = avg_df[pred_cols].mean(axis=1).round(2)
avg_df['avg_act_sl'] = avg_df[act_cols].mean(axis=1).round(2)

avg_df['avg_pred_act_gap'] = avg_df['avg_pred_sl'] - avg_df['avg_act_sl']
avg_df_cleaned = avg_df[['word1', 'word2','avg_pred_sl', 'avg_act_sl', 'avg_pred_act_gap']]
avg_df_cleaned_sorted = avg_df_cleaned.sort_values(by = 'avg_pred_act_gap', ascending = False)
avg_df_cleaned_sorted

    word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
463    收到    接受         5.53        0.91              4.62
194    荣誉    敬重         4.71        0.64              4.07
176    小说    作家         4.14        0.09              4.05
177    病人    复诊         4.24        0.36              3.88
374    记得     想         4.22        0.36              3.86
..    ...   ...          ...         ...               ...
190     洞    妻子         0.00        0.64             -0.64
355    失败   使气馁         2.34        3.00             -0.66
10    无实体    心灵         1.69        2.64             -0.95
89   有意义地    特别         1.92        3.00             -1.08
427    假设    预测         2.62        4.82             -2.20

[472 rows x 5 columns]

In [8]:
avg_df_cleaned_sorted.to_csv('average_diff.csv')

In [17]:
avg_df_cleaned

    word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
0       长    狭窄         0.56        0.27              0.29
1      内疚    羞愧         4.99        4.36              0.63
2      暴力    被动         0.09        0.00              0.09
3       闷    平庸         1.75        0.91              0.84
4      害羞    昂贵         0.00        0.00              0.00
..    ...   ...          ...         ...               ...
467    离开    走开         5.63        4.09              1.54
468     读    理解         3.54        0.64              2.90
469    装作    想像         2.46        0.18              2.28
470    跟随    追逐         4.03        2.82              1.21
471     加     除         0.77        0.45              0.32

[472 rows x 5 columns]

In [22]:
avg_df_cleaned.to_csv('average_diff_not_ordered_2.csv')