In [80]:
import pandas as pd
import numpy as np

In [81]:
# Import libraries and utils
%run "utils_a.ipynb"

In [82]:
avg_diff_gpt = 'F:/work_study/ILLC/S3B1/LLM project/implementation/evaluation/gpt/average_diff_gpt.csv'
avg_diff_doubao = 'F:/work_study/ILLC/S3B1/LLM project/implementation/evaluation/doubao/average_diff_doubao.csv'
f9_diff_gpt = 'F:/work_study/ILLC/S3B1/LLM project/implementation/evaluation/gpt/f9_diff.csv'
f9_diff_doubao = 'F:/work_study/ILLC/S3B1/LLM project/implementation/evaluation/doubao/f9_diff.csv'

In [83]:
df_gpt_f1f3f5f6 = pd.read_csv(avg_diff_gpt)
df_doubao_f1f3f5f6 = pd.read_csv(avg_diff_doubao)

In [84]:
df_gpt_f1f3f5f6

     Unnamed: 0 word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
0           463    收到    接受         5.53        0.91              4.62
1           194    荣誉    敬重         4.71        0.64              4.07
2           176    小说    作家         4.14        0.09              4.05
3           177    病人    复诊         4.24        0.36              3.88
4           374    记得     想         4.22        0.36              3.86
..          ...   ...   ...          ...         ...               ...
467         190     洞    妻子         0.00        0.64             -0.64
468         355    失败   使气馁         2.34        3.00             -0.66
469          10   无实体    心灵         1.69        2.64             -0.95
470          89  有意义地    特别         1.92        3.00             -1.08
471         427    假设    预测         2.62        4.82             -2.20

[472 rows x 6 columns]

In [85]:
df_doubao_f1f3f5f6

     Unnamed: 0 word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
0           441    安排    组织         5.14        0.82              4.32
1           463    收到    接受         5.03        0.91              4.12
2            86    看来    显然         6.00        1.91              4.09
3           342    钱包     袋         4.89        0.91              3.98
4           436    成长    增加         4.79        0.91              3.88
..          ...   ...   ...          ...         ...               ...
467          95    战斗    好斗         1.12        3.00             -1.88
468         171    幸福    和平         0.15        2.27             -2.12
469         368    接受    原谅         0.42        2.55             -2.13
470         340    月亮    行星         0.38        2.73             -2.35
471          89  有意义地    特别         0.43        3.00             -2.57

[472 rows x 6 columns]

In [86]:
# 取两个 DataFrame 的前 10 行
df_gpt_f1f3f5f6_top10 = df_gpt_f1f3f5f6.head(10)
df_doubao_f1f3f5f6_top10 = df_doubao_f1f3f5f6.head(10)

# 按两列筛选共有的行
top_common_rows_f1f3f5f6 = pd.merge(df_gpt_f1f3f5f6_top10, df_doubao_f1f3f5f6_top10, on=['word1', 'word2'])

# 查看共有的行
top_common_rows_f1f3f5f6

,Unnamed: 0_x,word1,word2,avg_pred_sl_x,avg_act_sl_x,avg_pred_act_gap_x,Unnamed: 0_y,avg_pred_sl_y,avg_act_sl_y,avg_pred_act_gap_y
0,463,收到,接受,5.53,0.91,4.62,463,5.03,0.91,4.12
1,245,蜜蜂,蚂蚁,4.22,0.45,3.77,245,4.08,0.45,3.63
2,446,装作,似乎,3.89,0.27,3.62,446,4.12,0.27,3.85

In [87]:
df_gpt_f1f3f5f6_top10

   Unnamed: 0 word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
0         463    收到    接受         5.53        0.91              4.62
1         194    荣誉    敬重         4.71        0.64              4.07
2         176    小说    作家         4.14        0.09              4.05
3         177    病人    复诊         4.24        0.36              3.88
4         374    记得     想         4.22        0.36              3.86
5         213  恶意软件    蠕虫         4.77        0.91              3.86
6         245    蜜蜂    蚂蚁         4.22        0.45              3.77
7         164     牛    山羊         4.18        0.45              3.73
8         165    血液    骨髓         4.00        0.36              3.64
9         446    装作    似乎         3.89        0.27              3.62

In [88]:
df_doubao_f1f3f5f6_top10

   Unnamed: 0 word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
0         441    安排    组织         5.14        0.82              4.32
1         463    收到    接受         5.03        0.91              4.12
2          86    看来    显然         6.00        1.91              4.09
3         342    钱包     袋         4.89        0.91              3.98
4         436    成长    增加         4.79        0.91              3.88
5         446    装作    似乎         4.12        0.27              3.85
6         245    蜜蜂    蚂蚁         4.08        0.45              3.63
7         336    电线    软线         4.81        1.18              3.63
8         405    混合    溶解         4.08        0.55              3.53
9         420    享受    娱乐         4.47        1.00              3.47

In [89]:
top_different_rows_f1f3f5f6 = pd.merge(df_gpt_f1f3f5f6_top10, df_doubao_f1f3f5f6_top10, 
                                       on=['word1', 'word2'],how='outer', indicator=True)
top_different_rows_f1f3f5f6

,Unnamed: 0_x,word1,word2,avg_pred_sl_x,avg_act_sl_x,avg_pred_act_gap_x,Unnamed: 0_y,avg_pred_sl_y,avg_act_sl_y,avg_pred_act_gap_y,_merge
0,463.0,收到,接受,5.53,0.91,4.62,463.0,5.03,0.91,4.12,both
1,194.0,荣誉,敬重,4.71,0.64,4.07,NaN,NaN,NaN,NaN,left_only
2,176.0,小说,作家,4.14,0.09,4.05,NaN,NaN,NaN,NaN,left_only
3,177.0,病人,复诊,4.24,0.36,3.88,NaN,NaN,NaN,NaN,left_only
4,374.0,记得,想,4.22,0.36,3.86,NaN,NaN,NaN,NaN,left_only
5,213.0,恶意软件,蠕虫,4.77,0.91,3.86,NaN,NaN,NaN,NaN,left_only
6,245.0,蜜蜂,蚂蚁,4.22,0.45,3.77,245.0,4.08,0.45,3.63,both
7,164.0,牛,山羊,4.18,0.45,3.73,NaN,NaN,NaN,NaN,left_only
8,165.0,血液,骨髓,4.00,0.36,3.64,NaN,NaN,NaN,NaN,left_only
9,446.0,装作,似乎,3.89,0.27,3.62,446.0,4.12,0.27,3.85,both
10,NaN,安排,组织,NaN,NaN,NaN,441.0,5.14,0.82,4.32,right_only
11,NaN,看来,显然,NaN,NaN,NaN,86.0,6.00,1.91,4.09,right_only
12,NaN,钱包,袋,NaN,NaN,NaN,342.0,4.89,0.91,3.98,right_only
13,NaN,成长,增加,NaN,NaN,NaN,436.0,4.79,0.91,3.88,right_only
14,NaN,电线,软线,NaN,NaN,NaN,336.0,4.81,1.18,3.63,right_only
15,NaN,混合,溶解,NaN,NaN,NaN,405.0,4.08,0.55,3.53,right_only
16,NaN,享受,娱乐,NaN,NaN,NaN,420.0,4.47,1.00,3.47,right_only

In [90]:
# 取两个 DataFrame 的后 10 行
df_gpt_f1f3f5f6_tail10 = df_gpt_f1f3f5f6.tail(10)
df_doubao_f1f3f5f6_tail10 = df_doubao_f1f3f5f6.tail(10)

# 按两列筛选共有的行
tail_common_rows_f1f3f5f6 = pd.merge(df_gpt_f1f3f5f6_tail10, df_doubao_f1f3f5f6_tail10, on=['word1', 'word2'])

# 查看共有的行
tail_common_rows_f1f3f5f6

,Unnamed: 0_x,word1,word2,avg_pred_sl_x,avg_act_sl_x,avg_pred_act_gap_x,Unnamed: 0_y,avg_pred_sl_y,avg_act_sl_y,avg_pred_act_gap_y
0,423,运输,电梯,0.93,1.45,-0.52,423,0.00,1.45,-1.45
1,89,有意义地,特别,1.92,3.00,-1.08,89,0.43,3.00,-2.57

In [91]:
df_gpt_f1f3f5f6_tail10

     Unnamed: 0  word1  word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
462          78  死气沉沉的  高高兴兴地         0.00        0.36             -0.36
463         116     丰富     许多         3.78        4.18             -0.40
464         306     花朵    忍耐力         0.02        0.45             -0.43
465          91    自豪的    谦逊地         0.00        0.45             -0.45
466         423     运输     电梯         0.93        1.45             -0.52
467         190      洞     妻子         0.00        0.64             -0.64
468         355     失败    使气馁         2.34        3.00             -0.66
469          10    无实体     心灵         1.69        2.64             -0.95
470          89   有意义地     特别         1.92        3.00             -1.08
471         427     假设     预测         2.62        4.82             -2.20

In [92]:
df_doubao_f1f3f5f6_tail10

     Unnamed: 0 word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
462         330     门    门口         2.24        3.64             -1.40
463         423    运输    电梯         0.00        1.45             -1.45
464         452    举起    提高         1.94        3.55             -1.61
465         361     听    听见         2.61        4.27             -1.66
466         289    朋友    宾客         1.42        3.18             -1.76
467          95    战斗    好斗         1.12        3.00             -1.88
468         171    幸福    和平         0.15        2.27             -2.12
469         368    接受    原谅         0.42        2.55             -2.13
470         340    月亮    行星         0.38        2.73             -2.35
471          89  有意义地    特别         0.43        3.00             -2.57

In [93]:
tail_different_rows_f1f3f5f6 = pd.merge(df_gpt_f1f3f5f6_tail10, df_doubao_f1f3f5f6_tail10, 
                                       on=['word1', 'word2'],how='outer', indicator=True)
tail_different_rows_f1f3f5f6

,Unnamed: 0_x,word1,word2,avg_pred_sl_x,avg_act_sl_x,avg_pred_act_gap_x,Unnamed: 0_y,avg_pred_sl_y,avg_act_sl_y,avg_pred_act_gap_y,_merge
0,78.0,死气沉沉的,高高兴兴地,0.00,0.36,-0.36,NaN,NaN,NaN,NaN,left_only
1,116.0,丰富,许多,3.78,4.18,-0.40,NaN,NaN,NaN,NaN,left_only
2,306.0,花朵,忍耐力,0.02,0.45,-0.43,NaN,NaN,NaN,NaN,left_only
3,91.0,自豪的,谦逊地,0.00,0.45,-0.45,NaN,NaN,NaN,NaN,left_only
4,423.0,运输,电梯,0.93,1.45,-0.52,423.0,0.00,1.45,-1.45,both
5,190.0,洞,妻子,0.00,0.64,-0.64,NaN,NaN,NaN,NaN,left_only
6,355.0,失败,使气馁,2.34,3.00,-0.66,NaN,NaN,NaN,NaN,left_only
7,10.0,无实体,心灵,1.69,2.64,-0.95,NaN,NaN,NaN,NaN,left_only
8,89.0,有意义地,特别,1.92,3.00,-1.08,89.0,0.43,3.00,-2.57,both
9,427.0,假设,预测,2.62,4.82,-2.20,NaN,NaN,NaN,NaN,left_only
10,NaN,门,门口,NaN,NaN,NaN,330.0,2.24,3.64,-1.40,right_only
11,NaN,举起,提高,NaN,NaN,NaN,452.0,1.94,3.55,-1.61,right_only
12,NaN,听,听见,NaN,NaN,NaN,361.0,2.61,4.27,-1.66,right_only
13,NaN,朋友,宾客,NaN,NaN,NaN,289.0,1.42,3.18,-1.76,right_only
14,NaN,战斗,好斗,NaN,NaN,NaN,95.0,1.12,3.00,-1.88,right_only
15,NaN,幸福,和平,NaN,NaN,NaN,171.0,0.15,2.27,-2.12,right_only
16,NaN,接受,原谅,NaN,NaN,NaN,368.0,0.42,2.55,-2.13,right_only
17,NaN,月亮,行星,NaN,NaN,NaN,340.0,0.38,2.73,-2.35,right_only

In [94]:
df_gpt_f9 = pd.read_csv(f9_diff_gpt)
df_gpt_f9

     Unnamed: 0 word1 word2  pred_sl  pred_sd  act_sl  act_sd  pred_act_gap
0            41    鼻子    嘴巴     3.93     0.26    0.09    0.32          3.84
1            87    蜥蜴    鳄鱼     4.00     0.00    0.45    0.97          3.55
2            98    收到    接受     4.40     0.51    0.91    1.41          3.49
3            93    装作    似乎     3.40     0.51    0.27    0.95          3.13
4            68    骨头    牙齿     3.73     0.46    0.64    0.97          3.09
..          ...   ...   ...      ...      ...     ...     ...           ...
113           6     笨     傻     4.93     0.26    5.27    0.67         -0.34
114           1   孩子气     傻     2.27     0.46    2.91    1.33         -0.64
115          14   无实体    心灵     1.67     0.49    2.64    1.95         -0.97
116          15  有意义地    特别     1.80     0.41    3.00    1.89         -1.20
117          91    假设    预测     2.93     0.26    4.82    0.42         -1.89

[118 rows x 8 columns]

In [95]:
df_doubao_f9 = pd.read_csv(f9_diff_doubao)
df_doubao_f9

     Unnamed: 0 word1 word2  pred_sl  pred_sd  act_sl  act_sd  pred_act_gap
0            98    收到    接受     3.73     0.46    0.91    1.41          2.82
1            54   裁判官    法官     6.00     0.00    3.55    1.49          2.45
2            89    降低    减少     6.00     0.00    3.82    1.99          2.18
3            25    领导    经理     4.00     0.00    2.00    0.99          2.00
4            13    强大    强大     6.00     0.00    4.36    0.70          1.64
..          ...   ...   ...      ...      ...     ...     ...           ...
113           1   孩子气     傻     0.93     0.88    2.91    1.33         -1.98
114           9    善良    大方     0.00     0.00    2.00    1.52         -2.00
115          81    逻辑    算术     0.00     0.00    2.09    1.63         -2.09
116           5    愉快    精彩     0.00     0.00    2.55    1.27         -2.55
117          15  有意义地    特别     0.00     0.00    3.00    1.89         -3.00

[118 rows x 8 columns]

In [96]:
# 取两个 DataFrame 的前 10 行
df_gpt_f9_top10 = df_gpt_f9.head(10)
df_doubao_f9_top10 = df_doubao_f9.head(10)

# 按两列筛选共有的行
top_common_rows_f9 = pd.merge(df_gpt_f9_top10, df_doubao_f9_top10, on=['word1', 'word2'])

# 查看共有的行
top_common_rows_f9

,Unnamed: 0_x,word1,word2,pred_sl_x,pred_sd_x,act_sl_x,act_sd_x,pred_act_gap_x,Unnamed: 0_y,pred_sl_y,pred_sd_y,act_sl_y,act_sd_y,pred_act_gap_y
0,98,收到,接受,4.40,0.51,0.91,1.41,3.49,98,3.73,0.46,0.91,1.41,2.82
1,79,男人,武士,3.27,0.46,0.55,0.70,2.72,79,2.00,0.00,0.55,0.70,1.45

In [97]:
df_gpt_f9_top10

   Unnamed: 0 word1 word2  pred_sl  pred_sd  act_sl  act_sd  pred_act_gap
0          41    鼻子    嘴巴     3.93     0.26    0.09    0.32          3.84
1          87    蜥蜴    鳄鱼     4.00     0.00    0.45    0.97          3.55
2          98    收到    接受     4.40     0.51    0.91    1.41          3.49
3          93    装作    似乎     3.40     0.51    0.27    0.95          3.13
4          68    骨头    牙齿     3.73     0.46    0.64    0.97          3.09
5          57     猫    狮子     3.93     0.26    0.91    1.62          3.02
6          79    男人    武士     3.27     0.46    0.55    0.70          2.72
7          75     床    毯子     2.67     0.62    0.09    0.32          2.58
8          73    吉他     鼓     2.93     0.59    0.36    0.70          2.57
9          82  威士忌酒  杜松子酒     4.20     0.41    1.64    1.65          2.56

In [98]:
df_doubao_f9_top10

   Unnamed: 0 word1 word2  pred_sl  pred_sd  act_sl  act_sd  pred_act_gap
0          98    收到    接受     3.73     0.46    0.91    1.41          2.82
1          54   裁判官    法官     6.00     0.00    3.55    1.49          2.45
2          89    降低    减少     6.00     0.00    3.82    1.99          2.18
3          25    领导    经理     4.00     0.00    2.00    0.99          2.00
4          13    强大    强大     6.00     0.00    4.36    0.70          1.64
5          69    规则    惯例     4.00     0.00    2.55    0.97          1.45
6          79    男人    武士     2.00     0.00    0.55    0.70          1.45
7          17    有时    每当     2.00     0.00    0.55    1.35          1.45
8          80    蝙蝠   吸血鬼     2.00     0.00    0.55    0.85          1.45
9          36    契约    协议     6.00     0.00    4.64    0.92          1.36

In [99]:
top_different_rows_f9 = pd.merge(df_gpt_f9_top10, df_doubao_f9_top10, 
                                       on=['word1', 'word2'],how='outer', indicator=True)
top_different_rows_f9

,Unnamed: 0_x,word1,word2,pred_sl_x,pred_sd_x,act_sl_x,act_sd_x,pred_act_gap_x,Unnamed: 0_y,pred_sl_y,pred_sd_y,act_sl_y,act_sd_y,pred_act_gap_y,_merge
0,41.0,鼻子,嘴巴,3.93,0.26,0.09,0.32,3.84,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,87.0,蜥蜴,鳄鱼,4.00,0.00,0.45,0.97,3.55,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,98.0,收到,接受,4.40,0.51,0.91,1.41,3.49,98.0,3.73,0.46,0.91,1.41,2.82,both
3,93.0,装作,似乎,3.40,0.51,0.27,0.95,3.13,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,68.0,骨头,牙齿,3.73,0.46,0.64,0.97,3.09,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,57.0,猫,狮子,3.93,0.26,0.91,1.62,3.02,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,79.0,男人,武士,3.27,0.46,0.55,0.70,2.72,79.0,2.00,0.00,0.55,0.70,1.45,both
7,75.0,床,毯子,2.67,0.62,0.09,0.32,2.58,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8,73.0,吉他,鼓,2.93,0.59,0.36,0.70,2.57,NaN,NaN,NaN,NaN,NaN,NaN,left_only
9,82.0,威士忌酒,杜松子酒,4.20,0.41,1.64,1.65,2.56,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,NaN,裁判官,法官,NaN,NaN,NaN,NaN,NaN,54.0,6.00,0.00,3.55,1.49,2.45,right_only
11,NaN,降低,减少,NaN,NaN,NaN,NaN,NaN,89.0,6.00,0.00,3.82,1.99,2.18,right_only
12,NaN,领导,经理,NaN,NaN,NaN,NaN,NaN,25.0,4.00,0.00,2.00,0.99,2.00,right_only
13,NaN,强大,强大,NaN,NaN,NaN,NaN,NaN,13.0,6.00,0.00,4.36,0.70,1.64,right_only
14,NaN,规则,惯例,NaN,NaN,NaN,NaN,NaN,69.0,4.00,0.00,2.55,0.97,1.45,right_only
15,NaN,有时,每当,NaN,NaN,NaN,NaN,NaN,17.0,2.00,0.00,0.55,1.35,1.45,right_only
16,NaN,蝙蝠,吸血鬼,NaN,NaN,NaN,NaN,NaN,80.0,2.00,0.00,0.55,0.85,1.45,right_only
17,NaN,契约,协议,NaN,NaN,NaN,NaN,NaN,36.0,6.00,0.00,4.64,0.92,1.36,right_only

In [100]:
# 取两个 DataFrame 的后 10 行
df_gpt_f9_tail10 = df_gpt_f9.tail(10)
df_doubao_f9_tail10 = df_doubao_f9.tail(10)

# 按两列筛选共有的行
tail_common_rows_f9 = pd.merge(df_gpt_f9_tail10, df_doubao_f9_tail10, on=['word1', 'word2'])

# 查看共有的行
tail_common_rows_f9

,Unnamed: 0_x,word1,word2,pred_sl_x,pred_sd_x,act_sl_x,act_sd_x,pred_act_gap_x,Unnamed: 0_y,pred_sl_y,pred_sd_y,act_sl_y,act_sd_y,pred_act_gap_y
0,81,逻辑,算术,2.07,0.70,2.09,1.63,-0.02,81,0.00,0.00,2.09,1.63,-2.09
1,1,孩子气,傻,2.27,0.46,2.91,1.33,-0.64,1,0.93,0.88,2.91,1.33,-1.98
2,15,有意义地,特别,1.80,0.41,3.00,1.89,-1.20,15,0.00,0.00,3.00,1.89,-3.00

In [101]:
tail_different_rows_f9 = pd.merge(df_gpt_f9_tail10, df_doubao_f9_tail10, 
                                       on=['word1', 'word2'],how='outer', indicator=True)
tail_different_rows_f9

,Unnamed: 0_x,word1,word2,pred_sl_x,pred_sd_x,act_sl_x,act_sd_x,pred_act_gap_x,Unnamed: 0_y,pred_sl_y,pred_sd_y,act_sl_y,act_sd_y,pred_act_gap_y,_merge
0,81.0,逻辑,算术,2.07,0.70,2.09,1.63,-0.02,81.0,0.00,0.00,2.09,1.63,-2.09,both
1,7.0,不需要,必须,0.13,0.35,0.18,0.63,-0.05,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,78.0,协议,条件,2.20,0.41,2.27,1.62,-0.07,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,71.0,章,选择,0.00,0.00,0.09,0.32,-0.09,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,4.0,怪诞,奇怪,4.40,0.51,4.64,1.08,-0.24,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,6.0,笨,傻,4.93,0.26,5.27,0.67,-0.34,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,1.0,孩子气,傻,2.27,0.46,2.91,1.33,-0.64,1.0,0.93,0.88,2.91,1.33,-1.98,both
7,14.0,无实体,心灵,1.67,0.49,2.64,1.95,-0.97,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8,15.0,有意义地,特别,1.80,0.41,3.00,1.89,-1.20,15.0,0.00,0.00,3.00,1.89,-3.00,both
9,91.0,假设,预测,2.93,0.26,4.82,0.42,-1.89,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,NaN,分界线,国境,NaN,NaN,NaN,NaN,NaN,26.0,2.00,0.00,3.18,1.45,-1.18,right_only
11,NaN,威士忌酒,杜松子酒,NaN,NaN,NaN,NaN,NaN,82.0,0.27,0.70,1.64,1.65,-1.37,right_only
12,NaN,床,家俱,NaN,NaN,NaN,NaN,NaN,33.0,2.13,0.52,3.55,1.26,-1.42,right_only
13,NaN,价值,价格,NaN,NaN,NaN,NaN,NaN,72.0,2.07,0.26,3.73,1.03,-1.66,right_only
14,NaN,抖动,搅拌,NaN,NaN,NaN,NaN,NaN,106.0,0.00,0.00,1.91,1.37,-1.91,right_only
15,NaN,善良,大方,NaN,NaN,NaN,NaN,NaN,9.0,0.00,0.00,2.00,1.52,-2.00,right_only
16,NaN,愉快,精彩,NaN,NaN,NaN,NaN,NaN,5.0,0.00,0.00,2.55,1.27,-2.55,right_only

In [102]:
avg_diff_gpt_not_ordered = 'F:/work_study/ILLC/S3B1/LLM project/implementation/evaluation/gpt/average_diff_not_ordered_gpt.csv'
avg_diff_doubao_not_ordered = 'F:/work_study/ILLC/S3B1/LLM project/implementation/evaluation/doubao/average_diff_not_ordered_doubao.csv'

In [103]:
gpt_original = pd.read_csv(avg_diff_gpt_not_ordered)
doubao_original = pd.read_csv(avg_diff_doubao_not_ordered)

In [104]:
print_correlation_and_pvalue(gpt_original,'avg_pred_sl', 'avg_act_sl')
print_pearson_correlation_and_pvalue(gpt_original,'avg_pred_sl', 'avg_act_sl')

Spearman's Rank correlation: 0.86869
P-value: 1.7194803150811514e-145
The correlation is statistically significant.

Pearson's correlation: 0.81757
P-value: 9.793222871269351e-115
The correlation is statistically significant.

In [138]:
print_correlation_and_pvalue(doubao_original,'avg_pred_sl', 'avg_act_sl')
print_pearson_correlation_and_pvalue(doubao_original,'avg_pred_sl', 'avg_act_sl')

Spearman's Rank correlation: 0.82245
P-value: 3.1376430586472672e-117
The correlation is statistically significant.

Pearson's correlation: 0.80708
P-value: 1.2912008437070103e-109
The correlation is statistically significant.

In [134]:
print_correlation_and_pvalue_cross(gpt_original, doubao_original, 'avg_pred_sl', 'avg_pred_sl')
print_pearson_correlation_and_pvalue_cross(gpt_original, doubao_original, 'avg_pred_sl', 'avg_pred_sl')

Spearman's Rank correlation: 0.88293
P-value: 1.9692724609576667e-156
The correlation is statistically significant.

Pearson's correlation: 0.86321
P-value: 1.2993355440647067e-141
The correlation is statistically significant.