In [2]:
import pandas as pd
import numpy as np

In [3]:
f1_diff = pd.read_csv('f1_diff.csv')
f3_diff = pd.read_csv('f3_diff.csv')
f5_diff = pd.read_csv('f5_diff.csv')
f6_diff = pd.read_csv('f6_diff.csv')

In [4]:
f1_diff

     Unnamed: 0 word1 word2  pred_sl  pred_sd  act_sl  act_sd  pred_act_gap
0             0     长    狭窄     0.00     0.00    0.27    0.32         -0.27
1             1    内疚    羞愧     6.00     0.00    4.36    1.34          1.64
2             2    暴力    被动     0.00     0.00    0.00    0.00          0.00
3             3     闷    平庸     0.00     0.00    0.91    1.14         -0.91
4             4    害羞    昂贵     0.00     0.00    0.00    0.00          0.00
..          ...   ...   ...      ...      ...     ...     ...           ...
467         467    离开    走开     5.40     0.51    4.09    1.32          1.31
468         468     读    理解     2.60     0.51    0.64    1.26          1.96
469         469    装作    想像     2.80     0.68    0.18    0.63          2.62
470         470    跟随    追逐     2.93     0.70    2.82    1.56          0.11
471         471     加     除     0.00     0.00    0.45    0.84         -0.45

[472 rows x 8 columns]

In [5]:
type(f1_diff['pred_act_gap'])

pandas.core.series.Series

In [6]:
avg_df = pd.DataFrame({
    'word1': f1_diff['word1'],
    'word2': f1_diff['word2'],
    'pred_sl_f1': f1_diff['pred_sl'],
    'pred_sl_f3': [np.nan] * 3 + list(f3_diff['pred_sl']),
    'pred_sl_f5': f5_diff['pred_sl'],
    'pred_sl_f6': f6_diff['pred_sl'],
    'act_sl_f1': f1_diff['act_sl'],
    'act_sl_f3': [np.nan] * 3 + list(f3_diff['act_sl']),
    'act_sl_f5': f5_diff['act_sl'],
    'act_sl_f6': f6_diff['act_sl'],
})
avg_df

,word1,word2,pred_sl_f1,pred_sl_f3,pred_sl_f5,pred_sl_f6,act_sl_f1,act_sl_f3,act_sl_f5,act_sl_f6
0,长,狭窄,0.00,NaN,1.5,0.00,0.27,NaN,0.27,0.27
1,内疚,羞愧,6.00,NaN,5.8,6.00,4.36,NaN,4.36,4.36
2,暴力,被动,0.00,NaN,0.8,0.00,0.00,NaN,0.00,0.00
3,闷,平庸,0.00,0.00,1.5,0.00,0.91,0.91,0.91,0.91
4,害羞,昂贵,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...
467,离开,走开,5.40,5.20,4.5,4.93,4.09,4.09,4.09,4.09
468,读,理解,2.60,2.73,2.1,3.07,0.64,0.64,0.64,0.64
469,装作,想像,2.80,2.87,4.5,3.60,0.18,0.18,0.18,0.18
470,跟随,追逐,2.93,4.00,4.5,2.80,2.82,2.82,2.82,2.82
471,加,除,0.00,0.00,0.0,0.00,0.45,0.45,0.45,0.45

In [12]:
pred_cols = [f'pred_sl_f{i}' for i in [1,3,5,6]]
act_cols = [f'act_sl_f{i}' for i in [1,3,5,6]]
avg_df['avg_pred_sl'] = avg_df[pred_cols].mean(axis=1).round(2)
avg_df['avg_act_sl'] = avg_df[act_cols].mean(axis=1).round(2)

avg_df['avg_pred_act_gap'] = avg_df['avg_pred_sl'] - avg_df['avg_act_sl']
avg_df_cleaned = avg_df[['word1', 'word2','avg_pred_sl', 'avg_act_sl', 'avg_pred_act_gap']]
avg_df_cleaned_sorted = avg_df_cleaned.sort_values(by = 'avg_pred_act_gap', ascending = False)
avg_df_cleaned_sorted

    word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
441    安排    组织         5.14        0.82              4.32
463    收到    接受         5.03        0.91              4.12
86     看来    显然         6.00        1.91              4.09
342    钱包     袋         4.89        0.91              3.98
436    成长    增加         4.79        0.91              3.88
..    ...   ...          ...         ...               ...
95     战斗    好斗         1.12        3.00             -1.88
171    幸福    和平         0.15        2.27             -2.12
368    接受    原谅         0.42        2.55             -2.13
340    月亮    行星         0.38        2.73             -2.35
89   有意义地    特别         0.43        3.00             -2.57

[472 rows x 5 columns]

In [8]:
avg_df_cleaned_sorted.to_csv('average_diff.csv')

In [14]:
avg_df_cleaned

    word1 word2  avg_pred_sl  avg_act_sl  avg_pred_act_gap
0       长    狭窄         0.50        0.27              0.23
1      内疚    羞愧         5.93        4.36              1.57
2      暴力    被动         0.27        0.00              0.27
3       闷    平庸         0.38        0.91             -0.53
4      害羞    昂贵         0.00        0.00              0.00
..    ...   ...          ...         ...               ...
467    离开    走开         5.01        4.09              0.92
468     读    理解         2.62        0.64              1.98
469    装作    想像         3.44        0.18              3.26
470    跟随    追逐         3.56        2.82              0.74
471     加     除         0.00        0.45             -0.45

[472 rows x 5 columns]

In [18]:
avg_df_cleaned.to_csv('average_diff_not_ordered_1.csv')